### PR TITLE
Use `bin/rspec` when available

### PR DESCRIPTION
**Pull request by twe4ked**

### CODE REVIEW

**Comment by jasoncodes** [comment]
I don’t know much about how Spring works but I thought you were supposed to invoke it via binstubs. Does `bin/rspec` start up any faster than `bundle exec spring rspec`?

**Comment by twe4ked** [comment]
I'll have a play and see.

**Comment by twe4ked** [comment]
I can't see a difference on this project, the times are jumping around by +-100 ms when running:

```
time bundle exec spring rspec spec/models/foo_spec.rb
# and
time bin/spring rspec spec/models/foo_spec.rb
```

I assumed you meant `bin/spring` not `bin/rspec`?

**Comment by jasoncodes** [comment]
I meant `bin/rspec`. See the README of https://github.com/jonleighton/spring-commands-rspec.

**Comment by twe4ked** [comment]
Just found that, I should have assumed you typed the correct thing... The bin stubs in this project aren't springified. Hmm.

**Comment by twe4ked** [comment]
Perhaps something that checks if `bin/rspec` has the spring code it uses that else it checks the `Gemfile.lock` else it falls back to the existing code.

**Comment by jasoncodes** [comment]
Possibly. I’d start by finding out what performance difference there is between `bundle exec spring rspec` and a springified bin stub.

**Comment by twe4ked** [comment]
Okay, `bin/*` is in the `.gitignore` so I can change it on this project anyway.

`bin/rspec` is double the speed of `bundle exec spring rspec` after running `bundle exec spring binstub --all`. Glad you asked.

My `bin/rspec` looks like this:

``` ruby
#!/usr/bin/env ruby
begin
  load File.expand_path("../spring", __FILE__)
rescue LoadError
end
require 'bundler/setup'
load Gem.bin_path('rspec-core', 'rspec')
```

We could do the check like `egrep -q "spring" bin/rspec` and run `bin/rspec` or perhaps something more specific.

**Comment by jasoncodes** [comment]
Just checking `[ -x bin/rspec ]` should be fine. If that passes we should either have a normal Bundler binstub or a Spring binstub. Either way, we should be able to use it in preference to `bundle exec rspec`.

**Comment by twe4ked** [comment]
Made changes as discussed.

**Comment by jasoncodes** [comment]
Looks good!

**Pull request merged**
